### ISSUE TITLE
Scaling and stretched images: Autoscale the longest side but not both

### ISSUE THREAD

**Issue by luftbuefel** [camrein/EzGraver#16]
Hi great software I really like it. Thank you so much for making it! I was wondering if it is possible to have newly loaded images autoscale to their longest side. It seems like right now when I load an image it scales the x and y to 100% fill in the allotted area. This results in a sometimes stretched image if the original is not a square. Why not check if the y length is larger than the x and if it is, find the scale for the y to fill 100% of the area, and then apply that same scale to the x to keep the proportion constant. Otherwise do the same but using the x length. 

It would also be great if we could change the scale of both simultaneously to make the picture uniformly smaller. I sometimes do this because I like to burn stamps out of art foam and my stamps are sometimes smaller than the max area.

Thanks for considering these issues!

**Comment by camrein** [comment]
Hi, thanks a lot for your appreciation and sorry for the late reply. 

As you have requested, I have just made a release which includes the possibility to preserve the aspect ratio of the original image (see [release v2.2.0](https://github.com/camrein/EzGraver/releases/tag/v2.2.0)). I hope it meets your expectations.

About your second request. Are you simply asking for a feature to manually scale the image? Could you please create a seperate issue for this, just to keep things a little bit ordered.

**Comment by polyglob** [comment]
Thanks for the prompt reply and enhancement! I will make a second issue for the manual image scaling feature request.

**Comment by camrein** [comment]
Thanks a lot for creating a separate issue. I close this one as it has been resolved.
