### ISSUE TITLE
Moving commands don't work on DK-8-KZ

### ISSUE THREAD

**Issue by AlexNk** [camrein/EzGraver#18]
With NEJE DK-8-KZ Left, Right, Up and Down buttons do nothing. 
I checked the code and found that it sends single byte (e.g. 0xf5) commands instead of (0xf5, 0x03) as native application does. The second byte is probably a number of pixels to move laser on.
It may be because of the difference between versions of software. But older (or different?) models of the printer could possible accept also two-byte commands.

UPDATE: After double-checking I found that in my version it uses the following commands to move the laser:
up: {0xf5, 0x01}
down:  {0xf5, 0x02}
left: {0xf5, 0x03}
right: {0xf5, 0x04}
Not sure if can be fit in the same protocol.

**Comment by camrein** [comment]
I have an NEJE JZ-5 and the move commands didn't work either. But as I didn't have a need the feature I was too lazy to check for the issue and left it as is. Poor excuse but that was the reason. :P
So first of all, thanks a lot for providing the codes. I will later check if these also work for mine.

Nevertheless, I'm currently unsure how I should implement it. As I have no idea if these buttons work for any machine at this time (or if there's actually someone who uses them), I don't feel like doing a hard-coded replacement. Probably a dropdown with the possibility to select the machine (or similar) is the most reasonable solution. Of course, feel free to provide better solutions.

**Comment by AlexNk** [comment]
Also I know how to retrieve burned pixels during printing:

connect(_ezGraver->serialPort().get(), &QSerialPort::readyRead, this,
&MainWindow::readyRead);
...
void MainWindow::readyRead()
{
    QByteArray data = _ezGraver->serialPort()->read(1024);

    //qDebug() << "received " << data.size() << " bytes: " << data.toHex();
    if ((data.size() == 5) && (data[0] == 0xff))
    {
        // pixel burned
        int x = data[1]*100 + data[2];
        int y = data[3]*100 + data[4];
        //_ui->progress->setValue(y * EzGraver::ImageHeight + x);
        // or
        // image->setPixel(x,y,...)
    } else
    if ((data.size() > 0) && (data[0] == 0x66))
    {
        // done
        //_ui->progress->setValue(EzGraver::ImageHeight *
EzGraver::ImageWidth);
    }
}


2017-04-10 17:47 GMT+03:00 Christoph Amrein <notifications@github.com>:

**Comment by camrein** [comment]
Thanks a lot for the code to compute and display progress. I have already experimented with possibilities to display the progress earlier (with the progress bar and an estimated time). There were some things that didn't quite fit in a desirable quality of the result without having to hacky code.
Long story short, I like your idea with simply computing the progress with the pixel position. This way, there is no need to distinguish between continue and restart actions.

**Comment by camrein** [comment]
So it took some time, but I have finally integrated the support for different protocols with pull request https://github.com/camrein/EzGraver/pull/24.

**Comment by AlexNk** [comment]
Tested on my device. Works correct. Thank you!
