### ISSUE TITLE
Manual scaling once an image has been loaded

### ISSUE THREAD

**Issue by polyglob** [camrein/EzGraver#19]
Could we have a button to scale a loaded image smaller (and larger perhaps) once it has been loaded into EzGraver.  Here is a usage scenario: I load an image into EzGraver to use for burning a rubber stamp. The stamp handle is about 3cm x 3cm and I want to scale down my image a touch before burning it.  I propose adding a button or a precise input box or slider that would let me scale the image uniformly to fit the item I wish to burn.

Keep up the great work, we all really appreciate the effort you have put into creating this program!

**Comment by camrein** [comment]
I have just implemented the requested feature with pull request https://github.com/camrein/EzGraver/pull/20. The new feature allows manual scaling of images on a range from 1% to 200% of the original image's size.
It will probably take a little bit until I release the updated version as I will most likely integrate the other remaining feature requests shortly.

**Comment by camrein** [comment]
I decided to release [v2.3.0](https://github.com/camrein/EzGraver/releases/tag/v2.3.0) with your requests without the other request to not delay it longer than necessary.
