### ISSUE TITLE
Can't launch on macOS

### ISSUE THREAD

**Issue by GilDev** [camrein/EzGraver#21]
Hi,
I run macOS 10.12.4 (latest), and when I try to run EzGraver's last release (2.3.0), here's what I get:
```
dyld: Library not loaded: @executable_path/../Frameworks/libEzGraverCore.1.dylib
  Referenced from: /Applications/EzGraverUi.app/Contents/MacOS/EzGraverUi
  Reason: image not found
```
Any idea on how to solve this? I also tried to build it from source following the instructions with no luck.
Thanks!

**Comment by camrein** [comment]
Hi

Thanks a lot for your report. I've investigated this issue and was able to resolve its cause. It appears that since version 2.1.0 the build server responsible for the OSX builds no longer packages the necessary libraries.

Therefore, please fallback to [v2.0.0](https://github.com/camrein/EzGraver/releases/tag/v2.0.0) until I have fixed it.

**Comment by GilDev** [comment]
Yeah version 2.0.0 launches. Thanks a lot!

**Comment by camrein** [comment]
The build should be fixed by now, and the newly released [v2.3.1](https://github.com/camrein/EzGraver/releases/tag/v2.3.1) should now work on OS X as well.

**Comment by GilDev** [comment]
Still cannot launch…

```
Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt@5.7/5.7.1/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /Applications/EzGraverUi.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
  Reason: image not found

Binary Images:
       0x10faf3000 -        0x10fb05ff7 +test.EzGraverUi (0) <4F57D6D5-3FDA-3911-9453-5913FF49A87F> /Applications/EzGraverUi.app/Contents/MacOS/EzGraverUi
       0x10fb17000 -        0x10fb1efff +libEzGraverCore.1.dylib (0) <5B05D689-AE83-3566-BBEB-0BD13413FE6E> /Applications/EzGraverUi.app/Contents/Frameworks/libEzGraverCore.1.dylib
       0x10fb28000 -        0x110026ff7 +org.qt-project.QtWidgets (5.7 - 5.7.1) <07745F14-81CC-3129-BD1B-8BCD45CA26AC> /Applications/EzGraverUi.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x110183000 -        0x1105d5fff +org.qt-project.QtGui (5.7 - 5.7.1) <BCD35856-390B-361F-9806-442DB90E8280> /Applications/EzGraverUi.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x1106c4000 -        0x110be3ff7 +org.qt-project.QtCore (5.7 - 5.7.1) <5E9BC277-7BA8-396A-B832-3008C55F8A89> /Applications/EzGraverUi.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x110c91000 -        0x110c9fff7 +org.qt-project.QtSerialPort (5.7 - 5.7.1) <39E65C37-EF4A-371A-8F34-590796086241> /Applications/EzGraverUi.app/Contents/Frameworks/QtSerialPort.framework/Versions/5/QtSerialPort
       0x118cf0000 -        0x118d2ddc7  dyld (433.5) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld
    0x7fff7934d000 -     0x7fff79351ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <EEB77D74-9B6B-331F-B103-5A62A029BCE2> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff7e580000 -     0x7fff7e585fff  com.apple.DiskArbitration (2.7 - 2.7) <A4DCD470-D8EA-37E9-BDCA-A2B469754C12> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff7ec7e000 -     0x7fff7ed13fff  com.apple.framework.IOKit (2.0.2 - 1324.50.21) <BA7DC917-35A9-3D1B-BBEC-ADF4495A166D> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff81eaa000 -     0x7fff81eb8fff  com.apple.opengl (14.0.16 - 14.0.16) <2970D284-D6BD-3727-AA74-2697AE676952> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff91293000 -     0x7fff91294ffb  libSystem.B.dylib (1238.51.1) <D9B20A4F-87BC-36CB-9405-80E105666725> /usr/lib/libSystem.B.dylib
    0x7fff91446000 -     0x7fff9149cff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
```

**Comment by camrein** [comment]
Thanks a lot for the prompt reply. It appears it no longer references the QT libraries correctly. This will need further investigations. However, this might taken a little bit more time as I do not have an OSX machine nearby.

**Comment by GilDev** [comment]
Well that's too bad, but thanks a lot for the support!
If you need macOS testing, just reply here or contact me elsewhere, I'll be happy to test within 24 hours. =)

**Comment by camrein** [comment]
I am grateful for any support. Feel free to give [v2.3.2](https://github.com/camrein/EzGraver/releases/tag/v2.3.2) a try.

**Comment by GilDev** [comment]
Yay, it works! =) I can't test right now the connection and controls of the engraver. Will do soon.
Feel free to ask anything you need about macOS, I have plenty of devices to test.

**Comment by camrein** [comment]
Great, thanks a lot for the quick review.

**Comment by bolstav** [comment]
Hi all.i have a small neje  engraver.  I have been trying to get it to work on my macbool pro running do captain but cant get it to work. 

I like the look of your software. 

Any chance of of giving me instructions on how to install it and the drivers please? 

I'm not a technical guy so an easy step by step way would be really appreciated.

Cheers heaps.
