### ISSUE TITLE
Linux Build on Mint (Ubuntu) is NOT working.

### ISSUE THREAD

**Issue by DiemenDesign** [camrein/EzGraver#66]
I just built the project after forking, and when trying to run `./EzGraver.pro` (as the only file I could see that looks like to run), as a normal user, and with elevated privileges, I get back `bash: ./EzGraver.pro: Permission denied` in both instances.

I've asked this before, is there an already built package available for various distros?

**Comment by DiemenDesign** [comment]
Upon changing the permissions of `EzGraver.pro` to be executed, I now get this with normal and elevated permissions:

````bash
./EzGraver.pro: line 1: TEMPLATE: command not found
./EzGraver.pro: line 3: CONFIG: command not found
./EzGraver.pro: line 5: SUBDIRS: command not found
````

I appreciate the availability and efforts of this project, but really, building and running the software needs to be much more simplified for those that a new to Linux, not everyone that uses Linux is good at doing these things, but still need/want to accomplish things like using external hardware without all the hassle, and this is why I've asked (2 times now) if there is a prepackaged binary, your able to do it for Mac and Win, why not Linux?

**Comment by innovate-invent** [comment]
You are running the wrong thing.
After compilation you run `make install` which will copy the compiled core library to the shared libraries folder on your system.
Then you run `./EzGraverUi/EzGraverUi` which is the actual binary file that has been generated.
